version: '3.9'
services:
  saludos:
    image: amazoncorretto:8
    networks:
    - mired
    volumes:
    - ./app:/app
    ports:
    - 8080:8080
    environment:
      MYSQL_HOST: db
    command:
    - java
    - -jar
    - /app/saludos.jar
    depends_on:
    - db
    links:
    - db
    restart: always
  db:
    image: mariadb
    networks:
      - mired
    environment:
      MARIADB_ROOT_PASSWORD: 123456
    volumes:
    - ./app:/docker-entrypoint-initdb.d
    - ./app/datos:/var/lib/mysql
networks:
  mired: